# Generated by Django 6.0 on 2026-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piro_index', '0002_video_thumbnail_alter_video_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_path',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
